### ISSUE TITLE
Error reading fchk file

### ISSUE THREAD

**Issue by shaoqx** [yangwangmadrid/EzReson#1]
HI,
I'm trying to use EzReson and reached the step that generate and exam LMOs. 
My error:
```
Traceback (most recent call last):
  File "/home/shaoqz/bin/EzReson//ezreson.py", line 503, in <module>
    runJob_LMO( p.basename )
  File "/home/shaoqz/bin/EzReson//ezreson.py", line 314, in runJob_LMO
    FchkInfo = readFchk( basename + '.fchk' )
  File "/home/shaoqz/bin/EzReson/readFchk.py", line 506, in readFchk
    NBas, NBasIndp, atIx, aoIx, E_tot, E_SCF, E, C, QMull
UnboundLocalError: local variable 'QMull' referenced before assignment
```
So I looked into the readFchk.py and found QMull search for a re pattern
`^\s*Mulliken\s+Charges\s+[A-Z]\s+[A-Z]+=\s+\d+.*`
But I do not even have the word `Mulliken` in my .fchk file. My fchk file was generated by `formchk` of gaussian09 and my structure was a doublet.
Do you have any suggestions on my case? Thank you!
Also is .gjf necessary for EzReson? The README says it should be together with .33 .fchk and .out but no in the WeChat paper.
***
My usage was:
TS-P.in:
```
File = TS-P-opt
Job = LMO 
```
In the command line:
`ezreson TS-P.in > TS-P.out`

And three file (.33 .fchk .out) was under the same dir generated by gaussian:
```
...
# uwb97xd/def2tzvp pop=nboread

Title

2 2
...
$NBO
  NOBOND
  AONAO=W
  archive file=TS-P-opt
$END
```

**Comment by shaoqx** [comment]
I see. The program does not support open-shell system yet. May I ask about when approximately the open-shell support would be online? Or is there any other way to do resonance analysis for doublet? Thank you!

**Comment by yangwangmadrid** [comment]
Yes, the current version of EzReson does not support open-shell wave functions.  We are starting working on implementing the algorithms to open-shell systems. Hopefully, this would be coming soon...

Yang

**Comment by shaoqx** [comment]
Thank you for the reply! Looking forward to your update! Struggling with this right now. Maybe I have to go for NRT or something else.
