### ISSUE TITLE
Unwanted covalent bonds in Lewis structures

### ISSUE THREAD

**Issue by FreemanTheMaverick** [yangwangmadrid/EzReson#2]
Hi.

I wanted to apply WFRT to H2N-Ph-Ph-NH2. Everything is fine except that its ordering is not as definite as that of a monocyclic molecule. The ordering I set is `Atoms = 14 4 3 2 1 6 5 7 8 10 12 11 9 13`, but four resonance structures that interest me given by `EzReson` have ridiculous covalent bonds `4-9`, `2-12`, `4-8` and `6-12`. They are 
```
   89    0.0904382232      26   56   49   77   86   24   92  105     14: 13: 3-2 6-5 1-7 8-10 12-11 4-9
   90    0.0904381388      14   56   49   77   43   89   92  105     14: 13: 4-3 6-5 1-7 8-10 2-12 11-9
   91    0.0904027302      26   56   49   20   82   89   92  105     14: 13: 3-2 6-5 1-7 4-8 10-12 11-9
   92    0.0904024906      26   18   49   77   60   89   92  105     14: 13: 3-2 4-5 1-7 8-10 6-12 11-9
```
What does this mean?
<img width="1208" alt="h2n-ph-ph-nh2" src="https://user-images.githubusercontent.com/63384635/172544533-786dc5fd-3af3-45d7-9e4c-98aef03f503d.png">

**Comment by yangwangmadrid** [comment]
Are these four resonance structures the most important ones? If they really are, the meaning of the "ridiculous" covalent bonds, e.g., 4-9, is that the contribution of the biradical form where the radicals are located at atoms 4 and 9 cannot be ignored, which reflects the delocalized nature of the pi electrons (meaning that only localized Kekulé structures are not sufficient for describing the electronic structure of the molecule).

In any case, I would suggest you to try to use a different, and IMO more appropriate, ordering  of atoms to define this bicyclic pi system. I may prefer the following ordering: 
14 4 3 2 1 7 9 11 13 12 10 8 7 1 6 5
In this way, the arrangement of atoms is as close as possible to a super cycle, which geometrically fulfills to the most extent Rumer's rule.
